### ISSUE TITLE
Possible regression caused in Coerce::Types::Standard by Type::Tiny 2.000001

### ISSUE THREAD

**Issue by orel1** [tobyink/p5-type-tiny#129]
Hello,

I wanted to test [Plerd](https://metacpan.org/dist/Plerd), but I encountered an error when installing the [Coerce::Types::Standard](https://metacpan.org/dist/Coerce-Types-Standard) module thought cpanm.

It seems that this error comes from Type::Tiny

By digging around, I found [this issue](https://rt.cpan.org/Public/Bug/Display.html?id=144542) on the bug tracker of Coerce::Types::Standard

In addition, [you will find attached the cpanm logs](https://github.com/tobyink/p5-type-tiny/files/10417078/build.log) corresponding to the installation of Coerce::Types::Standard. The error is as follows `Type library is immutable at /home/aurelien/.cache/cpanm/work/1673688973.17441/Coerce-Types-Standard-0.000007/blib/lib/Coerce/Types/Standard.pm line 81`

**Comment by tobyink** [comment]
Pretty sure it's because that module calls `__PACKAGE__->meta->make_immutable` at the end, but then adds new type constraints to the package later, at run time.

Between Type::Tiny 1.x and Type::Tiny 2.x, `make_immutable` was changed.

* In version 1.x, it makes all existing type constraints in your type library immutable.
* In version 2.x, it makes all existing type constraints in your type library immutable, and also stops new type constraints from being added.

This change was probably not documented as well as it should have been.

**Comment by orel1** [comment]
Thank you for this answer. The bug has been fixed by the maintainer of Coerce::Types::Standard

**Comment by tobyink** [comment]
Yep, I saw, but I'm keeping the ticket open for now as a reminder to better document this.
