### ISSUE TITLE
Add a **BoolLike** type to Types::TypeTiny

### ISSUE THREAD

**Issue by wchristian** [tobyink/p5-type-tiny#137]
The Bool constraint is rather strict: https://metacpan.org/dist/Type-Tiny/source/lib/Types/Standard.pm#L226

Compared to the Moose Bool constraint: https://metacpan.org/release/ETHER/Moose-2.2203/source/lib/Moose/Util/TypeConstraints/Builtins.pm#L44

This causes JSON::MaybeXS::true and JSON::MaybeXS::false to be rejected.

Maybe the stringification could be adopted?

**Comment by tobyink** [comment]
This is by design.

Moose and Mouse's implementations of **Bool** are each bizarre in their own special ways. Moose accepts overloaded objects, but only cares that the `q("")` overload results in undef, an empty string, or the strings "0" or "1" and *completely ignores the `q(bool)` overload*. Mouse in PurePerl mode acts like Moose, but in XS mode will respect the `q(bool)` overload for false values, but the `q("")` overload for true values. *Utter chaos!*

Types::Standard instead follows the (admittedly vague) Moose *documentation* which states:

> Bool accepts 1 for true, and undef, 0, or the empty string as false.

And makes no explicit mention of overloaded objects. So that's what Types::Standard's **Bool** accepts. Just those four values.

Types::Standard's **Bool** type does, however, have a coercion defined for it. If you set `coerce => 1` for a boolean, then it will accept *any* value and coerce it via `!!$_`, basically typecasting any incoming value to a true boolean.

**Comment by tobyink** [comment]
I'd certainly consider adding a **BoolLike** type to Types::Common instead though. That library already has **StringLike**, **CodeLike**, **ArrayLike**, and **HashLike** which accept overloaded objects.

**Comment by wchristian** [comment]
That sounds good, if you like i can do a PR. :)

**Comment by tobyink** [comment]
This is included in Types::TypeTiny 2.003_000 on CPAN. I should release a stable version some time this month.

**Comment by wchristian** [comment]
Oooh, lovely. A small thought: Maybe have the docs on that link to overload.pm?

Otherwise, i'll be trialing it over the next week. :)

**Comment by bpj** [comment]
This broke my code because I had imported everything matching `/Like$` from Types::TypeTiny and then had my own BoolLike type which wouldn't load. Took me two hours to find out why! 😄 

Anyway this is great! Does it also check stringification to `1, 0` or only numification? What would be the arguments against accepting objects with such stringification?
