### ISSUE TITLE
I had to define inline_as to get my coercions working.

### ISSUE THREAD

**Issue by Mekk** [tobyink/p5-type-tiny#14]
_Beware: I am just learning Type::Tiny (together with Moo) and this is possible I completely misunderstand sth. Still..._

In short: it turned out, I _must_ define inline_as (even if I do not care) to have my checks and coercions working, without them my where and coercions were completely ignored. And finding out what is going on was very hard (quote-inlined code in debugger, tasty...).

Longer: I created some type library, mostly following manual, but making rather trivial types. For example

``` perl
 declare BankAccountNo,
      as Str,
      where { 
          $_ =~ /^\d{26}$/                 
          or $_ =~ /^[A-Z]{2}\d{18,26}$/   
          or $_ = ~/^\d{8}-\d+(-\d+)+$/
          ;
      },
      message { "Bad account: $_"};
```

I also made coercion responsible for dropping spaces 

``` perl
coerce BankAccountNo,
      from Str, via {
          say "Coercing account $_";
          $_ =~ s{\s+}{}g;
          $_;
      },
```

and I tried using it in some Moo class:

``` perl
has 'base_acc' => (is=>'ro', required=>1,
                               isa=>BankAccountNo, coerce=>BankAccountNo->coercion);
```

To my amazement, when I gave my class string like "10 2030 4050 1111 2222 3333 4444" as base_acc, it landed unmodified as attribute value.

After diagnosing things for some time I found, that Moo part is working (if I give some other routine as coerce, it is called), but:
a) my „where” is not called at all, instead some inherited inlined version is called
and
b) if this succeeds, coercion is not called.

Once I added inline_as (which replicated the same check as made in where), things started to work (my inline_as failed so coercion was fired)

**Comment by assistcontrol** [comment]
Toby, can you speak as to this? I'm completely baffled trying to get coercions to work at all. Copying the examples from the POD and stuff in examples/  verbatim, I can't get the coercions to fire.

Either the `where` and `inline_as` clauses are successful, in which case coercions never fire, or `where` and `inline_as` clauses fail, in which case the coercion fires and then the program `die`s because the `where` clause failed.

All of the coercion examples use custom objects or involve ArrayRef/HashRef.

Here's an example that doesn't even use Moo, but doesn't make coercions fire:

```
use feature 'say';
use Type::Library -base;
use Type::Utils;
use Types::Standard qw(Int Str);

declare "MyType", as Str;
coerce "MyType",
       	from Str, via { "String: $_" },
       	from Int, via { "Integer: $_" }
;

say to_MyType(42);
say to_MyType("string");
```

This prints:
```
42
string
```
instead of what I would have thought would be:
```
Integer: 42
String: string
```
Can you provide some insight in what else is needed to get coercions to fire?

If I add
```
coerce "MyType", from Undef, via { "Undef!" };
say to_MyType(undef)
```
that works. Is Type::Tiny just not identifying the input as a Str or Int?

**Comment by tobyink** [comment]
@assistcontrol "42" is a string.

**Comment by tobyink** [comment]
@Mekk, you had me worried for a moment.

```
$_ = ~/^\d{8}-\d+(-\d+)+$/
```

The problem is in your code. `=~` is not the same as `= ~`.
