### ISSUE TITLE
Globally deactivate validation

### ISSUE THREAD

**Issue by jsf116** [tobyink/p5-type-tiny#78]
As mentioned in the previous issue opened by me, our team tries to migrate from **Params::Validate** to **Type::Params**.
For performance reasons a global deactivation of validation would be very useful: during the development and test phases the validation is on, but once an application is in production, the validation can usually be deactivated because in the most cases the arguments applied to the functions / methods in this application can be considered staying valid.
The performance gain is especially significant in case of daemons written in Perl.

**Params::Validate** uses for this purpose the environment variable **PERL_NO_VALIDATION**.
We would like to have something similar deactivating both the compilation and the subsequent validation provided by **Type::Params**.

Thanks and Regards,
jsf

**Comment by tobyink** [comment]
By "deactivate", I guess what is essentially meant is "always pass without really checking".

The problem is there are codepaths like:

```perl
if ( HashRef->check( $thing ) ) {
  ...;
}
else {
  ...;
}
```

If the `HashRef->check(...)` simply returns true without really checking, it will result in the first codepath being taken instead of the second codepath. And even if you think you'll never do that, perhaps you're using a third-party library which uses Type::Tiny, so you might break something in that library by disabling validation globally.

[Type::Tiny::Manual::Optimization](https://typetiny.toby.ink/Optimization.html) provides some hints for optimization. In particular, one of the hints is to use Devel::StrictMode. This allows you to do stuff like:

```perl
use Moo;
use Types::Standard -types;
use Devel::StrictMode;

has hashref_of_ints => (
  is  => 'ro',
  isa => STRICT ? HashRef[Int] : HashRef,
);
```

When you wanted to use the stricter test (`HashRef[Int]`) in your development environment you would set `$ENV{'PERL_STRICT'}` to true. When you wanted to use the faster less strict test (`HashRef`) in your live environment, you would set `$ENV{'PERL_STRICT'}` to false.

And also make sure you've got Type::Tiny::XS installed. With it installed, even some fairly complex tests like `HashRef[ArrayRef[Int]]` can be tested entirely in XS, so are pretty quick.

**Comment by jsf116** [comment]
Thank you for the explanation and for the hint!
